name: CI

on:
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Check code style
      run: dotnet format --verify-no-changes --no-restore
    - name: Build
      run: dotnet build --no-restore
